import type { LucideIcon } from "lucide-react";
import { Building2, CalendarHeart, MapPinned, MountainSnow, Plane, TrainFront, UsersRound } from "lucide-react";

export const contact = {
  phone: "+33 6 67 80 01 01",
  phoneHref: "tel:+33667800101",
  whatsapp: "https://wa.me/33667800101",
  email: "MexVTC@gmail.com",
  emailHref: "mailto:MexVTC@gmail.com",
  address: "23 Boulevard de Lattre de Tassigny, 69140 Rillieux-la-Pape, France",
};

export type PageConfig = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  intro: string;
  description: string[];
  highlights: string[];
  related: string[];
  image: "hero" | "alps" | "corporate" | "wedding";
  icon: LucideIcon;
};

export const pages: PageConfig[] = [
  { slug:"vtc-lyon", title:"VTC Lyon", metaTitle:"VTC Lyon | Chauffeur privé MEXVTC", metaDescription:"Réservez votre chauffeur VTC à Lyon : tarif fixe, berline ou van premium et prise en charge personnalisée.", eyebrow:"Lyon & métropole", intro:"Votre chauffeur privé pour circuler à Lyon avec sérénité.", description:["MEXVTC organise vos déplacements privés et professionnels à Lyon et dans sa métropole. Chaque trajet est préparé à l’avance avec un prix annoncé avant le départ.","D’un rendez-vous en Presqu’île à une liaison vers l’aéroport ou une course longue distance, votre chauffeur assure une prise en charge ponctuelle dans un véhicule premium."], highlights:["Tarif annoncé avant le départ","Berline et van Mercedes","Service privé sur réservation","Trajets locaux et longue distance"], related:["chauffeur-prive-lyon","vtc-aeroport-lyon","gare-part-dieu","tarifs"], image:"hero", icon:MapPinned },
  { slug:"chauffeur-prive-lyon", title:"Chauffeur privé Lyon", metaTitle:"Chauffeur privé Lyon | MEXVTC", metaDescription:"Chauffeur privé à Lyon pour transferts, mise à disposition, tourisme et déplacements professionnels.", eyebrow:"Service sur mesure", intro:"Un service discret, ponctuel et adapté à votre programme.", description:["Profitez d’un chauffeur privé à Lyon pour un transfert unique ou une mise à disposition. Votre itinéraire, vos horaires et vos contraintes sont pris en compte dès la réservation.","La mise à disposition convient aux journées de rendez-vous, événements, visites privées et programmes nécessitant plusieurs arrêts."], highlights:["Accueil personnalisé","Mise à disposition horaire","Connaissance locale","Confort à bord"], related:["vtc-entreprise-lyon","notre-flotte","tarifs","reserver"], image:"corporate", icon:UsersRound },
  { slug:"vtc-aeroport-lyon", title:"VTC Aéroport Lyon Saint-Exupéry", metaTitle:"VTC Aéroport Lyon Saint-Exupéry | MEXVTC", metaDescription:"Transfert privé entre Lyon et l’aéroport Saint-Exupéry avec suivi de vol, accueil et tarif fixe.", eyebrow:"Transfert aéroport", intro:"Votre arrivée suivie, votre chauffeur prêt, votre trajet déjà organisé.", description:["L’aéroport Lyon-Saint-Exupéry se situe à environ 25 km de Lyon, soit approximativement 30 minutes par la route selon les conditions de circulation.","Votre chauffeur suit l’horaire du vol, vous accueille avec une pancarte nominative, vous aide avec les bagages et vous conduit directement à destination."], highlights:["Suivi du vol","Attente en cas de retard","Accueil avec pancarte","Aide aux bagages"], related:["accueil-aeroport-lyon","vtc-lyon","notre-flotte","reserver"], image:"hero", icon:Plane },
  { slug:"accueil-aeroport-lyon", title:"Accueil Aéroport Lyon", metaTitle:"Accueil Aéroport Lyon | Chauffeur MEXVTC", metaDescription:"Meet & greet à Lyon Saint-Exupéry : chauffeur avec pancarte, suivi du vol et aide aux bagages.", eyebrow:"Meet & greet", intro:"Dès l’atterrissage, un accueil clair et sans attente inutile.", description:["Votre chauffeur surveille l’arrivée de votre vol et ajuste la prise en charge en cas de retard. À votre sortie, il vous attend au point convenu avec une pancarte à votre nom.","Après la prise en charge de vos bagages, vous rejoignez votre véhicule privé pour un transfert direct vers Lyon ou votre destination."], highlights:["Vol surveillé","Pancarte nominative","Bagages pris en charge","Départ direct"], related:["vtc-aeroport-lyon","notre-flotte","tarifs","reserver"], image:"hero", icon:Plane },
  { slug:"gare-part-dieu", title:"Transfert Gare Part-Dieu", metaTitle:"VTC Gare Part-Dieu Lyon | MEXVTC", metaDescription:"Chauffeur VTC à la gare Lyon Part-Dieu : accueil sur réservation et transfert privé vers votre destination.", eyebrow:"Transfert gare", intro:"Une liaison fluide entre votre TGV et votre prochaine destination.", description:["Réservez votre chauffeur pour une arrivée ou un départ à la gare Lyon Part-Dieu. Communiquez votre numéro de TGV afin de faciliter la coordination de la prise en charge.","Le service convient aux voyageurs seuls, familles et groupes grâce au choix entre berline et van."], highlights:["Coordination avec votre TGV","Accueil personnalisé","Berline ou van","Destination au choix"], related:["vtc-lyon","vtc-entreprise-lyon","notre-flotte","reserver"], image:"corporate", icon:TrainFront },
  { slug:"vtc-entreprise-lyon", title:"VTC Entreprise Lyon", metaTitle:"VTC Entreprise Lyon | Chauffeur business MEXVTC", metaDescription:"Transport professionnel à Lyon : rendez-vous, aéroport, mise à disposition et journée avec chauffeur.", eyebrow:"Business class", intro:"La ponctualité et la discrétion au service de vos rendez-vous.", description:["MEXVTC accompagne dirigeants, collaborateurs et invités pour leurs déplacements professionnels à Lyon et au-delà.","Organisez un transfert aéroport, une succession de rendez-vous ou une mise à disposition à l’heure, à la demi-journée ou à la journée."], highlights:["Ponctualité professionnelle","Transferts corporate","Chauffeur à l’heure ou à la journée","Véhicules premium"], related:["chauffeur-prive-lyon","vtc-aeroport-lyon","tarifs","reserver"], image:"corporate", icon:Building2 },
  { slug:"vtc-rhone-alpes", title:"VTC Rhône-Alpes", metaTitle:"VTC Rhône-Alpes au départ de Lyon | MEXVTC", metaDescription:"Chauffeur privé pour vos trajets en Rhône-Alpes depuis Lyon, en berline ou van, avec tarif annoncé.", eyebrow:"Au-delà de Lyon", intro:"Des liaisons privées vers les villes et massifs de la région.", description:["Depuis Lyon, rejoignez Grenoble, Annecy, Chambéry, Saint-Étienne, les Alpes et les autres destinations desservies sur réservation.","Les trajets longue distance sont réalisés en véhicule privé, avec une organisation adaptée aux bagages et des pauses planifiées lorsque nécessaire."], highlights:["Départ de Lyon","Longue distance","Pauses planifiées","Tarif clair"], related:["chauffeur-prive-grenoble","chauffeur-prive-annecy","transfert-stations-ski-alpes","reserver"], image:"alps", icon:MapPinned },
  { slug:"chauffeur-prive-grenoble", title:"Chauffeur privé Grenoble", metaTitle:"Chauffeur privé Grenoble depuis Lyon | MEXVTC", metaDescription:"Transfert privé Lyon–Grenoble et déplacements avec chauffeur professionnel sur réservation.", eyebrow:"Destination Grenoble", intro:"Une liaison directe et confortable entre Lyon et Grenoble.", description:["Réservez une berline ou un van avec chauffeur pour rejoindre Grenoble depuis Lyon, l’aéroport ou une autre destination.","Votre prix est communiqué avant validation et votre trajet est organisé selon vos horaires et bagages."], highlights:["Trajet privé direct","Berline ou van","Prix annoncé","Réservation anticipée"], related:["vtc-rhone-alpes","transfert-stations-ski-alpes","notre-flotte","reserver"], image:"alps", icon:MountainSnow },
  { slug:"chauffeur-prive-annecy", title:"Chauffeur privé Annecy", metaTitle:"Chauffeur privé Annecy depuis Lyon | MEXVTC", metaDescription:"Transfert premium vers Annecy en berline ou van avec chauffeur MEXVTC.", eyebrow:"Destination Annecy", intro:"Annecy en toute tranquillité, au départ de Lyon.", description:["MEXVTC assure vos transferts privés vers Annecy dans un véhicule premium adapté à votre groupe.","La course est préparée à l’avance afin de vous apporter visibilité sur le prix et simplicité le jour du départ."], highlights:["Service porte à porte","Véhicule privé","Bagages accueillis","Tarification claire"], related:["vtc-rhone-alpes","transfert-stations-ski-alpes","notre-flotte","reserver"], image:"alps", icon:MapPinned },
  { slug:"chauffeur-prive-nice", title:"Chauffeur privé Nice", metaTitle:"Chauffeur privé Nice | MEXVTC", metaDescription:"Chauffeur privé et transfert longue distance vers Nice en véhicule premium.", eyebrow:"Destination Côte d’Azur", intro:"Un voyage privé vers Nice, sans rupture de charge.", description:["Pour un déplacement vers Nice, MEXVTC propose une liaison longue distance privée depuis Lyon et sa région.","Profitez d’un véhicule premium, d’un chauffeur professionnel et de pauses organisées au rythme du trajet."], highlights:["Longue distance privée","Pauses planifiées","Confort premium","Bagages avec vous"], related:["transfert-aeroport-nice-vtc","chauffeur-prive-marseille","notre-flotte","reserver"], image:"hero", icon:MapPinned },
  { slug:"transfert-aeroport-nice-vtc", title:"Transfert Aéroport Nice VTC", metaTitle:"Transfert Aéroport Nice VTC | MEXVTC", metaDescription:"Transfert privé vers ou depuis l’aéroport Nice Côte d’Azur avec chauffeur professionnel.", eyebrow:"Aéroport Nice", intro:"Votre transfert aéroport privé sur la Côte d’Azur.", description:["Réservez une prise en charge vers ou depuis l’aéroport de Nice avec un chauffeur professionnel.","Les informations de vol transmises à la réservation facilitent la coordination de votre accueil et de votre départ."], highlights:["Informations de vol","Accueil organisé","Berline ou van","Trajet privé"], related:["chauffeur-prive-nice","chauffeur-prive-toulon","notre-flotte","reserver"], image:"hero", icon:Plane },
  { slug:"chauffeur-prive-marseille", title:"Chauffeur privé Marseille", metaTitle:"Chauffeur privé Marseille | MEXVTC", metaDescription:"Transfert longue distance vers Marseille avec chauffeur privé, berline ou van.", eyebrow:"Destination Marseille", intro:"Reliez Lyon et Marseille dans le confort d’un véhicule privé.", description:["MEXVTC propose des trajets longue distance vers Marseille pour les particuliers et professionnels.","Votre chauffeur adapte les arrêts nécessaires et vous conduit directement à l’adresse convenue."], highlights:["Porte à porte","Tarif avant départ","Pauses organisées","Service professionnel"], related:["chauffeur-prive-toulon","chauffeur-prive-nice","notre-flotte","reserver"], image:"hero", icon:MapPinned },
  { slug:"chauffeur-prive-toulon", title:"Chauffeur privé Toulon", metaTitle:"Chauffeur privé Toulon | MEXVTC", metaDescription:"Transfert privé vers Toulon en berline ou van avec chauffeur professionnel MEXVTC.", eyebrow:"Destination Toulon", intro:"Une liaison longue distance sereine jusqu’à Toulon.", description:["Voyagez vers Toulon sans correspondance, avec vos bagages et dans un véhicule réservé à votre groupe.","Le tarif et les modalités sont communiqués avant la confirmation du trajet."], highlights:["Véhicule réservé","Bagages à bord","Prix confirmé","Chauffeur professionnel"], related:["chauffeur-prive-marseille","chauffeur-prive-nice","notre-flotte","reserver"], image:"hero", icon:MapPinned },
  { slug:"vtc-villeurbanne", title:"VTC Villeurbanne", metaTitle:"VTC Villeurbanne | Chauffeur MEXVTC", metaDescription:"Réservez un chauffeur VTC à Villeurbanne pour Lyon, les gares, l’aéroport et vos trajets privés.", eyebrow:"Métropole de Lyon", intro:"Votre chauffeur à Villeurbanne, pour les trajets du quotidien comme les grands départs.", description:["MEXVTC dessert Villeurbanne pour vos rendez-vous, transferts gare et aéroport ou courses longue distance.","La réservation permet de choisir votre horaire et le véhicule correspondant au nombre de voyageurs et de bagages."], highlights:["Villeurbanne et métropole","Gares et aéroport","Tarif annoncé","Berline ou van"], related:["vtc-lyon","gare-part-dieu","vtc-aeroport-lyon","reserver"], image:"corporate", icon:MapPinned },
  { slug:"transfert-stations-ski-alpes", title:"Transfert Stations de Ski Alpes", metaTitle:"Transfert stations de ski Alpes | MEXVTC", metaDescription:"Transfert privé depuis Lyon vers Courchevel, La Plagne, Tignes, Val d’Isère et Val Thorens.", eyebrow:"Alpes françaises", intro:"Les stations alpines en véhicule privé, avec l’espace nécessaire pour vos bagages.", description:["MEXVTC dessert sur réservation Courchevel, La Plagne, Tignes, Val d’Isère et Val Thorens depuis Lyon et sa région.","Le van Mercedes Classe V permet d’accueillir groupes et bagages dans de bonnes conditions de confort."], highlights:["Courchevel & La Plagne","Tignes & Val d’Isère","Val Thorens","Van jusqu’à 7–8 passagers"], related:["vtc-rhone-alpes","van","notre-flotte","reserver"], image:"alps", icon:MountainSnow },
  { slug:"vtc-mariage-lyon", title:"VTC Mariage Lyon", metaTitle:"VTC Mariage Lyon | Chauffeur événement MEXVTC", metaDescription:"Voiture avec chauffeur pour mariage et événement privé à Lyon. Demandez votre devis personnalisé.", eyebrow:"Mariages & événements", intro:"Une présence élégante et une organisation précise pour vos moments importants.", description:["Pour un mariage, une réception ou une occasion privée à Lyon, MEXVTC organise vos déplacements selon le programme de l’événement.","Demandez un devis en précisant les horaires, lieux, nombre de passagers et véhicule souhaité."], highlights:["Programme personnalisé","Berline ou van","Coordination des horaires","Devis sur demande"], related:["berline","van","notre-flotte","reserver"], image:"wedding", icon:CalendarHeart },
];

export const destinationNames = ["Lyon","Lyon Saint-Exupéry Airport","Geneva","Grenoble","Annecy","Aix-en-Provence","Aix-les-Bains","Avignon","Beaune","Besançon","Bourg-en-Bresse","Chalon-sur-Saône","Chambéry","Clermont-Ferrand","Courchevel","Dijon","La Plagne","Lausanne","Mâcon","Marseille","Montélimar","Montpellier","Le Puy-en-Velay","Saint-Étienne","Tignes","Toulon","Valence","Val d’Isère","Val Thorens"];

export const faq = [
  ["Le prix est-il connu à l’avance ?","Oui. Le tarif est annoncé avant la validation de la réservation : pas de compteur ni de surprise à l’arrivée."],
  ["Que se passe-t-il si mon vol est retardé ?","Votre chauffeur suit les informations du vol et adapte l’heure d’accueil en cas de retard signalé."],
  ["Combien de passagers peuvent voyager ?","La berline accueille jusqu’à 4 passagers. Le van convient à 7 à 8 passagers selon la configuration."],
  ["Quelle capacité pour les bagages ?","La berline accueille 2 bagages. Le van peut accueillir jusqu’à 7 bagages, selon leur format."],
  ["Comment réserver un trajet ?","Utilisez le formulaire en ligne, appelez le +33 6 67 80 01 01 ou contactez MEXVTC sur WhatsApp."],
  ["Peut-on réserver un chauffeur à la journée ?","Oui. La mise à disposition est proposée à l’heure, à la demi-journée ou à la journée complète."],
  ["Quelle différence entre un VTC et un taxi ?","Un VTC intervient sur réservation avec un prix défini avant la course. Il ne pratique pas la maraude avec compteur."],
  ["Comment se passe l’accueil à l’aéroport ?","Votre chauffeur suit le vol, vous attend au point convenu avec une pancarte nominative et vous aide avec les bagages."],
];

export const pricing = {
  berline: [
    ["Lyon → Lyon","35 €"],["Lyon → proche agglomération","50 €"],["Lyon → Saint-Exupéry","75 €"],["Lyon → Genève","390 €"],
  ],
  van: [["Lyon → Lyon","55 €"],["Lyon → proche agglomération","75 €"],["Lyon → Saint-Exupéry","95 €"],["Lyon → Genève","440 €"]],
  availability: [["À l’heure","70 € / heure"],["Demi-journée (4h30)","à partir de 320 €"],["Journée complète (8h30)","à partir de 480 €"]],
  vanAvailability: [["À l’heure","80 € / heure"],["Demi-journée (4h30)","à partir de 370 €"],["Journée complète (8h30)","à partir de 570 €"]],
};
