import { Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, BriefcaseBusiness, CarFront, Check, Clock3, Luggage, MapPin, PlaneLanding, ShieldCheck, Sparkles, UserRoundCheck, Wifi } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { destinationNames, faq, pages, pricing } from "@/lib/mexvtc-data";
import hero from "@/assets/mexvtc-hero.jpg";
import alps from "@/assets/mexvtc-alps.jpg";
import corporate from "@/assets/mexvtc-corporate.jpg";
import wedding from "@/assets/mexvtc-wedding.jpg";

export const images={hero,alps,corporate,wedding};
export function SectionHeading({eyebrow,title,text,invert=false}:{eyebrow:string;title:string;text?:string;invert?:boolean}){return <div className={`section-heading ${invert?"text-ink-foreground":""}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text&&<p className={invert?"text-ink-muted":"text-muted-foreground"}>{text}</p>}</div>}
export function TrustStrip(){return <div className="border-y border-border bg-background"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-border md:grid-cols-4 md:divide-y-0">{[[ShieldCheck,"Tarif fixe","Connu avant départ"],[UserRoundCheck,"Chauffeurs VTC","Carte professionnelle"],[PlaneLanding,"Vol suivi","Jusqu’à 60 min d’attente"],[CarFront,"Mercedes","Berline & van"]].map(([Icon,t,s])=><div className="flex items-center gap-3 px-5 py-5" key={String(t)}><Icon className="size-5 shrink-0 text-primary"/><div><strong className="block text-sm">{String(t)}</strong><span className="text-xs text-muted-foreground">{String(s)}</span></div></div>)}</div></div>}
export function ServicesGrid(){const featured=pages.filter(p=>["vtc-lyon","vtc-aeroport-lyon","vtc-entreprise-lyon","gare-part-dieu","transfert-stations-ski-alpes","vtc-mariage-lyon"].includes(p.slug)); return <section className="section"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="Nos services" title="Un chauffeur pour chaque temps fort." text="Aéroport, affaires, gare, longues distances ou événements : un service pensé autour de votre programme."/><div className="service-grid">{featured.map((p,i)=><Link key={p.slug} to={`/${p.slug}`} className="service-card reveal-group"><img src={images[p.image]} alt="Service de chauffeur privé MEXVTC" loading="lazy" width={1600} height={1000}/><span className="service-number">0{i+1}</span><div><p>{p.eyebrow}</p><h3>{p.title}</h3><span>{p.intro}</span><b>Découvrir <ArrowRight/></b></div></Link>)}</div></div></section>}
export function FixedPrice(){return <section className="overflow-hidden bg-ink text-ink-foreground"><div className="mx-auto grid max-w-7xl lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-[480px]"><img src={hero} alt="Mercedes avec chauffeur à Lyon" loading="lazy" width={1600} height={1000} className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-ink/10 to-ink"/></div><div className="flex flex-col justify-center px-6 py-16 lg:px-16"><SectionHeading invert eyebrow="Tarif fixe & sans surprise" title="Un tarif clair avant même votre départ." text="Vous connaissez le prix avant de monter à bord. Le trafic ne déclenche aucun compteur et les modalités sont confirmées avant votre course."/><div className="mt-8 grid gap-5 sm:grid-cols-2">{["Prix annoncé avant réservation","Aucun compteur","Retard de vol pris en compte","Véhicule entièrement privé"].map((x,i)=><div className="price-proof" key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div><Button asChild variant="champagne" size="lg" className="mt-9 self-start"><Link to="/tarifs">Consulter les tarifs <ArrowRight/></Link></Button></div></div></section>}
export function AirportJourney(){const stages=[[PlaneLanding,"Le vol atterrit"],[Clock3,"Votre vol est suivi"],[UserRoundCheck,"Accueil nominatif"],[Luggage,"Aide aux bagages"],[CarFront,"Départ privé"],[MapPin,"Votre destination"]];return <section className="section bg-soft"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="Lyon-Saint-Exupéry" title="De la passerelle à votre destination." text="À environ 25 km de Lyon — approximativement 30 minutes par la route selon la circulation."/><div className="mt-8 rounded-sm border border-border bg-background p-6"><p className="font-display text-2xl">Vol retardé ?</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Le suivi de vol et jusqu’à 60 minutes d’attente en cas de retard sont inclus dans le tarif aéroport indiqué.</p></div></div><ol className="journey">{stages.map(([Icon,t],i)=><li key={String(t)}><span><Icon/></span><div><small>Étape {i+1}</small><h3>{String(t)}</h3></div></li>)}</ol></div></div></section>}
export function DestinationMap(){const [selected,setSelected]=useState("Lyon Saint-Exupéry Airport"); const page:Record<string,string>={Grenoble:"/chauffeur-prive-grenoble",Annecy:"/chauffeur-prive-annecy",Marseille:"/chauffeur-prive-marseille",Toulon:"/chauffeur-prive-toulon",Nice:"/chauffeur-prive-nice",Courchevel:"/transfert-stations-ski-alpes","La Plagne":"/transfert-stations-ski-alpes",Tignes:"/transfert-stations-ski-alpes","Val d’Isère":"/transfert-stations-ski-alpes","Val Thorens":"/transfert-stations-ski-alpes","Lyon Saint-Exupéry Airport":"/vtc-aeroport-lyon"}; return <section id="destinations" className="section bg-ink text-ink-foreground"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading invert eyebrow="Destinations" title="Lyon comme point de départ." text="Sélectionnez une destination desservie pour préparer votre trajet privé."/><div className="mt-12 grid overflow-hidden border border-ink-foreground/15 lg:grid-cols-[1.2fr_.8fr]"><div className="route-map"><div className="map-orbit orbit-one"/><div className="map-orbit orbit-two"/><div className="lyon-pin"><span/>Lyon</div><div className="destination-pin"><span/>{selected}</div><svg viewBox="0 0 800 450" aria-hidden="true"><path d="M175 300 C 320 120, 470 350, 650 155"/></svg><p>France · Suisse · Alpes</p></div><div className="bg-ink-panel p-6 lg:p-9"><p className="eyebrow">Itinéraire sélectionné</p><h3 className="font-display text-3xl">Lyon <span className="text-primary">→</span> {selected}</h3><p className="mt-3 text-sm leading-6 text-ink-muted">Trajet privé en berline ou van. Demandez votre tarif fixe selon votre date et vos horaires.</p><Button asChild variant="champagne" className="mt-6"><Link to={page[selected]||"/reserver"}>Voir le trajet <ArrowRight/></Link></Button><div className="mt-7 max-h-64 overflow-y-auto border-t border-ink-foreground/15 pt-5"><div className="flex flex-wrap gap-2">{destinationNames.filter(x=>x!=="Lyon").map(x=><button type="button" className={`destination-chip ${selected===x?"is-active":""}`} onClick={()=>setSelected(x)} key={x}>{x}</button>)}</div></div></div></div></div></section>}
export function FleetShowcase(){const [type,setType]=useState<"berline"|"van">("berline"); const van=type==="van"; return <section className="section"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div className="fleet-image"><img src={van?alps:hero} alt={van?"Mercedes Classe V MEXVTC":"Mercedes Classe E ou S MEXVTC"} loading="lazy" width={1600} height={1000}/><span>{van?"7–8":"1–4"}<small>passagers</small></span></div><div><SectionHeading eyebrow="Notre flotte" title={van?"Mercedes Classe V":"Mercedes Classe E / S"} text={van?"L’espace premium pour les groupes, familles et bagages.":"Le confort discret d’une berline d’affaires."}/><div className="segment-control"><button type="button" className={!van?"is-active":""} onClick={()=>setType("berline")}>Berline</button><button type="button" className={van?"is-active":""} onClick={()=>setType("van")}>Van</button></div><div className="mt-7 grid grid-cols-2 gap-px bg-border">{[[UsersRoundIcon,van?"7–8 passagers":"4 passagers"],[Luggage,van?"Jusqu’à 7 bagages":"2 bagages"],[Wifi,"Wi-Fi à bord"],[Sparkles,"Rafraîchissements & presse"]].map(([Icon,t])=><div className="bg-background p-4" key={String(t)}><Icon className="mb-3 size-5 text-primary"/><span className="text-sm">{String(t)}</span></div>)}</div><Button asChild size="lg" className="mt-7"><Link to={van?"/van":"/berline"}>Découvrir ce véhicule <ArrowRight/></Link></Button></div></div></div></section>}
const UsersRoundIcon=BriefcaseBusiness;
export function PricingBlock(){const [type,setType]=useState<"berline"|"van">("berline"); const rows=pricing[type]; const hire=type==="van"?pricing.vanAvailability:pricing.availability; return <section className="section bg-soft"><div className="mx-auto max-w-5xl px-5 lg:px-8"><SectionHeading eyebrow="Tarifs indicatifs" title="Votre trajet, votre prix — avant le départ." text="Les tarifs ci-dessous sont indicatifs. Le prix exact est confirmé lors de votre demande."/><div className="segment-control mx-auto mt-8 max-w-sm"><button type="button" className={type==="berline"?"is-active":""} onClick={()=>setType("berline")}>Berline</button><button type="button" className={type==="van"?"is-active":""} onClick={()=>setType("van")}>Van</button></div><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="pricing-table"><h3>Transferts</h3>{rows.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="pricing-table"><h3>Mise à disposition</h3>{hire.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div><div className="mt-7 text-center"><Button asChild size="lg"><Link to="/reserver">Demander mon tarif <ArrowRight/></Link></Button></div></div></section>}
export function FaqBlock(){return <section className="section"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><SectionHeading eyebrow="Questions fréquentes" title="Tout savoir avant votre trajet." text="Une réservation simple, un prix annoncé et un accueil préparé."/><Accordion type="single" collapsible className="border-t border-border">{faq.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger className="py-5 text-base">{q}</AccordionTrigger><AccordionContent className="max-w-2xl pb-5 leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>}
